# General params
result_dir: mrna_full_basic
data_dir: ../data
data: ../data/mrna_full_hek.csv # path to raw data csv
seed: 2023
gpus: [0,1]

# Params related to training
train:
  train_bs: 32 #Trainin batch size
  val_bs: 16 #Validation batch size
  lr: 1e-4 #Learning rate
  epoch: 30 # Training epoch
  val_epoch: 5 #Validate in each this epoch
  grad_acc: 1 #Gradient_accumulations steps

# Params related to building dataset
dataset:
  vocab_file: configs/vocab.txt
  max_length: 5000
  pad_on_left: False
  pad_token: 0
  pad_token_segment_id: 0
  mask_padding_with_zero: True

# Params related to Performer models
models:
  num_tokens: 69
  max_seq_len: 5002
  dim: 768
  depth: 2
  heads: 12
  dim_head: 64
  local_attn_heads: 0
  local_window_size: 256
  causal: False
  ff_mult: 4
  nb_features: Null
  feature_redraw_interval: 1000
  reversible: False
  ff_chunks: 1
  ff_glu: False
  emb_dropout: 0.
  ff_dropout: 0.
  attn_dropout: 0.
  generalized_attention: False
  kernel_fn: nn.ReLU()
  use_scalenorm: False
  use_rezero: False
  cross_attend: False
  no_projection: False
  tie_embed: False
  rotary_position_emb: True
  axial_position_emb: False
  axial_position_shape: Null
  auto_check_redraw: True
  qkv_bias: False
  attn_out_bias: False
  shift_tokens: False
  label_num : 1
