# General params
result_dir: mrna_fiveonly_cnn_step_scheduler
wandb_project : mrna_te_pred
data_dir: ../data
data: ../data/mrna_five_hek.csv # path to raw data csv
seed: 2023
gpus: [0,1]

# Params related to training
train:
  train_bs: 32 #Trainin batch size
  val_bs: 16 #Validation batch size
  lr: 1e-3 #Learning rate
  epoch: 300 # Training epoch
  val_epoch: 5 #Validate in each this epoch
  grad_acc: 1 #Gradient_accumulations steps

# Params related to CNN model
model:
  max_len: 500
  conv1_ch: 120
  conv2_ch: 120
  conv3_ch: 120
  conv1_kernel: 8
  conv2_kernel: 8
  conv3_kernel: 8
  linear1_dim : 128
  linear2_dim : 32


# Params related to building dataset
dataset:
  regions : ["fiveprime"]
  vocab_file: configs/vocab.txt
  max_length: 5000
  pad_on_left: False
  pad_token: 0
  pad_token_segment_id: 0
  mask_padding_with_zero: True


